export type AnyZodRawShape = Record<string, unknown>
export type ForkSessionOptions = Record<string, unknown>
export type ForkSessionResult = { sessionId: string }
export type GetSessionInfoOptions = Record<string, unknown>
export type GetSessionMessagesOptions = Record<string, unknown>
export type InferShape<T> = T extends AnyZodRawShape ? Record<string, unknown> : never
export type InternalOptions = Record<string, unknown>
export type InternalQuery = Record<string, unknown>
export type ListSessionsOptions = Record<string, unknown>
export type McpSdkServerConfigWithInstance = Record<string, unknown>
export type Options = Record<string, unknown>
export type Query = Record<string, unknown>
export type SDKSession = Record<string, unknown>
export type SDKSessionOptions = Record<string, unknown>
export type SdkMcpToolDefinition<T> = Record<string, unknown>
export type SessionMessage = Record<string, unknown>
export type SessionMutationOptions = Record<string, unknown>
